global using HarmonyLib;
global using ToyBox.Infrastructure;
global using ToyBox.Infrastructure.Patching;
global using ToyBox.Infrastructure.Blueprints;
global using ToyBox.Infrastructure.Enums;
global using ToyBox.Infrastructure.Utilities.Strings;
global using static ToyBox.Infrastructure.Logging;
global using static ToyBox.Infrastructure.GeneralSettings;
global using static ToyBox.Infrastructure.Utilities.Helpers;
global using static ToyBox.Infrastructure.LayoutHelper;
global using static ToyBox.Infrastructure.StringExtensions;
global using static ToyBox.Infrastructure.Blueprints.BlueprintLoader;
