name: Build Mod on PR

on:
  pull_request:
      types: [labeled]
  pull_request_target:
      types: [labeled]

jobs:

  build:
    if: ${{ github.event_name == 'pull_request' && github.event.label.name == 'safe to test' }}
    runs-on: windows-latest
    permissions:
      contents: read
      packages: read

    steps:
    - name: Build
      id: build-action
      uses: xADDBx/BuildOwlcatMod@v2
      with:
        GAME_NAME: Wrath
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_NAME: ${{ github.repository_owner }}
        PACKAGE_OWNER: xADDBx
        BRANCH_REF: ${{ github.event.pull_request.head.sha }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.zipFile }}
        path: ${{ env.outDir }}

  # Consume the label separately; permissions issue blabla
  remove-test-label:
    if: ${{ github.event_name == 'pull_request_target' && github.event.label.name == 'safe to test' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Remove Test Label
      shell: bash
      run: |
        curl --silent --fail-with-body \
        -X DELETE \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ github.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/safe%20to%20test'
