name: Create Release for new Tag

on:
  push:
    tags:        
      - '**'

jobs:

  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: read

    steps:
    - name: Build
      id: build-action
      uses: xADDBx/BuildOwlcatMod@v2
      with:
        GAME_NAME: Wrath
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_NAME: ${{ github.repository_owner }}
        PACKAGE_OWNER: xADDBx

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.zipFile }}
        path: ${{ env.outDir }}
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.zipFilePath }}\*.zip
        name: ${{ env.ZipFile }} built for Wrath ${{ env.gameVersionNum }}${{ env.gameVersionSuffix }}

    - name: Extract Version from zipFile
      shell: pwsh
      run: |
        $version = ($env:zipFile -split '-')[-1]
        echo "MOD_VERSION=$version" >> $env:GITHUB_ENV

    - name: Upload to NexusMods
      uses: Nexus-Mods/upload-action@main
      with:
        api_key: ${{ secrets.NEXUSMODS_API_KEY }}
        file_group_id: 164587
        filename: ${{ env.zipFilePath }}\${{ env.zipFile }}.zip
        version: ${{ env.MOD_VERSION }}
        display_name: ToyBox